services:
  nginx:
    image: nginx:1.29-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "50MB"

  api1: &api
    build: .
    hostname: api1
    environment:
      - APP_PORT=8080
      - DB_URL=postgres://user:password@db:5432/rinha?sslmode=disable
      - VALKEY_URL=valkey:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_ID=API-1
      - WORKER_CONCURRENCY=16
    networks:
      - backend
      - payment-processor
    depends_on:
      valkey:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: "100MB"

  api2:
    <<: *api
    hostname: api2
    environment:
      - APP_PORT=8080
      - DB_URL=postgres://user:password@db:5432/rinha?sslmode=disable
      - VALKEY_URL=valkey:6379
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - INSTANCE_ID=API-2
      - WORKER_CONCURRENCY=16

  valkey:
    image: valkey/valkey:8.1.3-alpine
    container_name: rinha-valkey
    command: valkey-server --save "" --appendonly no --maxclients 20000 --io-threads 4 --io-threads-do-reads yes
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "valkey-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "100MB"
          
networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
